name: CI build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  ZipPrefix: CrcLauncher
  Version: "0.0.${{ github.event.number }}.${{ github.run_number }}"

jobs:
  build:
    name: "CI build"
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64, arm64]

    steps:
      - name: Build, zip, and lint
        uses: ./build-zip-lint.yml
        with:
          version: ${{ env.Version }}
          architecture: ${{ matrix.architecture }}
          zipPrefix: ${{ env.ZipPrefix }}
