name: CI build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  Version: "0.0.${{ github.event.number }}.${{ github.run_number }}"

jobs:
  setup:
    runs-on: windows-latest
    outputs:
      Version: ${{ env.Version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  build:
    needs: [setup]
    uses: ./.github/workflows/build-zip-lint.yml
    name: "CI build"
    strategy:
      matrix:
        architecture: [x64, arm64]
    with:
      version: ${{ needs.setup.outputs.Version }}
      architecture: ${{ matrix.architecture }}
