name: CI build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  Version: "0.0.${{ github.event.number }}.${{ github.run_number }}"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64, arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build, zip, and lint
        uses: ./github/actions/build-zip-lint
        with:
          version: ${{ env.Version }}
          architecture: ${{ matrix.architecture }}
