name: CI build

on:
  pull_request:
    branches:
      - main

env:
  Name: "" # Default value, replaced by the Extract env from files step.
  PROJECTNAME: "" # Default value, replaced by the Remove .dll from environment variable step.
  TARGETFRAMEWORK: "" # Default value, replaced by the Extract env from files step.

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64, arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract env from files
        uses: ./.github/actions/env-from-source
        with:
          manifest-file: ./src/plugin.json
          manifest-paths: |
            Name
            ExecuteFileName
          project-file: ./src/Community.PowerToys.Run.Plugin.CrcLauncher.csproj
          project-paths: |
            /root/PropertyGroup/TargetFramework

      - name: Remove .dll from environment variable
        shell: pwsh
        run: |
          $TrimmedValue = $env:EXECUTEFILENAME -replace '\.dll$', ''
          Write-Output "PROJECTNAME=$TrimmedValue" | Out-File -Append -FilePath $env:GITHUB_ENV

      - name: Build, zip, and lint
        uses: ./.github/actions/build-zip-lint
        with:
          version: "0.${{ github.event.number }}.${{ github.run_number }}"
          architecture: ${{ matrix.architecture }}
          buildFolderName: ${{ env.NAME }}
          projectName: ${{ env.PROJECTNAME }}
          targetFramework: ${{ env.TARGETFRAMEWORK }}
