name: Release application

on:
  release:
    types: [created]

# This method of passing environment varaibles to a reusable workflow comes from
# https://github.com/orgs/community/discussions/26671
jobs:
  setup:
    runs-on: windows-latest
    outputs:
      Version: ${{ steps.get_version.outputs.version-without-v }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get the release version
        id: get_version
        uses: dhkatz/get-version-action@v3.0.0

  build:
    name: "Release build"
    runs-on: windows-latest
    needs: [setup]
    strategy:
      matrix:
        architecture: [x64, arm64]

    steps:
      - name: Build, zip, and lint
        id: build-zip-lint
        uses: ./.github/workflows/build-zip-lint.yml
        with:
          version: ${{ needs.setup.outputs.Version }}
          architecture: ${{ matrix.architecture }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.build-zip-lint.outputs.zipFile }}

      - name: Upload checksums
        uses: wangzuo/action-release-checksums@v1
