name: Release application

on:
  release:
    types: [created]

env:
  ZipPrefix: CrcLauncher

jobs:
  build:
    name: "Release build"
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64, arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get the release version
        id: get_version
        uses: dhkatz/get-version-action@v3.0.0

      - name: Build, zip, and lint
        uses: ./.github/workflows/build-zip-lint.yml
        with:
          version: ${{ steps.get_version.outputs.version-without-v }}
          architecture: ${{ matrix.architecture }}
          zipPrefix: ${{ env.ZipPrefix }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./${{ env.ZipPrefix}}-${{ steps.get_version.outputs.version-without-v}}-${{ matrix.architecture }}.zip

      - name: Upload checksums
        uses: wangzuo/action-release-checksums@v1
